// Code generated by stacker -type float64 ; DO NOT EDIT

package main

type float64Stack struct {
	data []float64
}

func (s *float64Stack) Push(v float64) {
	s.data = append(s.data, v)
}

func (s *float64Stack) Pop() (v float64, ok bool) {
	if len(s.data) == 0 {
		return v, false
	}
	top := len(s.data) - 1
	v = s.data[top]
	s.data = s.data[:top]
	return v, true
}

func (s *float64Stack) Peek() (v float64, ok bool) {
	if len(s.data) == 0 {
		return v, false
	}
	top := len(s.data) - 1
	v = s.data[top]
	return v, true
}

func (s *float64Stack) Len() int {
	return len(s.data)
}

func (s *float64Stack) Walk(f func(float64)) {
	for _, v := range s.data {
		f(v)
	}
}

func (s *float64Stack) Rotate() {
	if len(s.data) == 0 {
		return
	}

	top := len(s.data) - 1
	s.data = append(s.data[top:], s.data[:top]...)
}

func (s *float64Stack) Unrotate() {
	if len(s.data) == 0 {
		return
	}

	bottom := 0
	s.data = append(s.data[bottom+1:], s.data[bottom])
}
